# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: PATIL AKSHAY VILAS VAISHALI
title: Senior Data Scientist
email: akshaypatil15@gmail.com
# website: www.github.com/akshaypatil15

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: akshaypatil15
github_username:  akshaypatil15
stackoverflow_username: "6459275"
instagram_username: chief_akshay
# twitter_username: akshaypatil15
# facebook_username: appy15
# pinterest_username: akshaypatil15
# youtube_username: "64113981"

# Additional icon links
additional_links:
- title: wordpress
  icon: fab fa-wordpress
  url: https://chiefakshaypatil.wordpress.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Akshay and I'm a senior data scientist with 4 years of industrial experience in building solutions for Computer Vision as well as 
  Natural Language problems. Proven success in creating and deploying machine learning solutions.

  I am most skilled in: <mark>Python</mark>, <mark>Data Science</mark>, <mark>Machine Learning</mark> and <mark>Capturing Nature through lens</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MS Course Project
        # link: 
        # link_text: Project Website
        # additional_links:
        #  - title:  akshaypatil15/getTextFromPDF
        #    icon: fab fa-github
        #    url: https://github.com/Akshaypatil15/getTextFromPDF.git
          # - title:  Github page for project (eg. akshaypatil15/getTextFromPDF)
          #   icon: fab fa-github
          #   url: Link to project (eg. https://github.com/Akshaypatil15/getTextFromPDF.git)
        quote: >
          NEURAL NETWORK FOR CLASSIFICATION OF STARS AND GALAXIES.
        description: | # this will include new lines to allow paragraphs
          - Created a pipeline to download FITS files from <mark>Sloan Digital Sky Survey(SDSS)</mark> sky observatory and converted files into images (numpy array).
          - Developed a star-galaxy classification framework that uses a <mark>Neural Network</mark> model on these images.
          - Trained model using <mark>Convolution Neural Network</mark> with the help of <mark>TensorFlow</mark> library.

      - layout: left
        title: Pdf to Text
        link: https://github.com/Akshaypatil15/getTextFromPDF
        link_text: getTextFromPDF
        # additional_links:
        #  - title:  modern-resume-theme
        #    icon: fab fa-github
        #    url: boringcompany.com
          # - title:  Github page for project (eg. akshaypatil15/getTextFromPDF)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Google Cloud Platform implementation for text detection and recognition.
        description: | # this will include new lines to allow paragraphs
          - I started this project as a way to learn <mark>GCP</mark> and it has since grown into a fully end-to-end python project.
          - I have learned many skills after this and been I'm very proud of having this in my profile.

      - layout: left
        title: Freelance
        #link: PROJECT_LINK
        #link_text: LINK_CAPTION
        # additional_links:
        #  - title:  modern-resume-theme
        #    icon: fab fa-github
        #    url: boringcompany.com
          # - title:  Github page for project (eg. akshaypatil15/getTextFromPDF)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Few freelacing projects done by me.
        description: | # this will include new lines to allow paragraphs
          - Developed a machine learning based python program to detect mobile manufacturer names using mobile images.
          - Applied statistical method for image generation in multiple NFT projects.
          - Created a neural network project which can classify currency notes.
          - Applied Deep Learning method for Character Recognition in Devanagari Languages.

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Quantech Data Science LLP, Navi Mumbai
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Data Scientist
        caption: December 2019 - Present
        quote: >
          AUTOMATING INVOICE PROCESSING
        description: | # this will include new lines to allow paragraphs
            - Designed solution architectures for the product and ensured its production quality from data-ops perspective.
            - Establish proper monitoring of online/offline models and perform re-training whenever necessary, preferably through an automated procedure.
            - Facilitated machine learning model experiments at scale.
            - Development and maintenance of <mark>docker</mark> containers on cloud platforms.

        quote: >
          TDS RECONCILIATION ENGINE
        description: | # this will include new lines to allow paragraphs
            - Developed a python-based project which can get and read input files from the server.
            - Applied govt defined rules to get TDS calculations and updating into <mark>MS-SQL Server</mark>.
            - Converted the whole process into a docker container and deployed to <mark>Microsoft Azure</mark>.

        quote: >
          ITR Data Extraction
        description: | # this will include new lines to allow paragraphs
            - Designed and developed python pipeline using NLP technique to get required information.
            - Implemented <mark>FASK service</mark> for communication with other programs.

      - layout: left
        title: Cere Labs Pvt. Ltd., Mumbai
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: October 2018 - November 2019
        quote: >
          Artificial Intelligence research and deveploment.
        description: | # this will include new lines to allow paragraphs
            - Collecting different types of printed documents and applying pre-processing and cleaning methods.
            - Applied and evaluated OCR problems by using deep learning algorithms such as <mark>CNN</mark>, <mark>FRCNN</mark>, etc.
            - Design, Developed and tested NLP algorithms such as <mark>RNN</mark>, <mark>LSTM</mark>, etc to get insights from given text.
            - Used <mark>TensorFlow Serving</mark> to deploy models for production use and deployed models with the help of AWS/GCP cloud services.
            - Developed and improved a few documents information extraction automation for such as Bank Account Statements, CIBIL Report, KYC Documents.
            - Developed end to end machine learning pipeline for Electricity Metre Reading, Data masking on sensitive information.

      - layout: left
        title: Cere Labs Pvt. Ltd., Mumbai
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Project Fellow
        caption: September 2018 - September 2018
        quote: >
          Contribute to aspects of research strategy within the department.
        description: | # this will include new lines to allow paragraphs
            - Maintaining digital record of the results in presentable format.
            - Identifying methods for <mark>Text Detection</mark> as well as <mark>Recognition</mark> in Printed Documents.

      - layout: left
        title: Cere Labs Pvt. Ltd., Mumbai
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Internship
        caption: Feburary 2018 - May 2018
        quote: >
          Galaxy Detection Using Artificial Intelligence.
        description: | # this will include new lines to allow paragraphs
            - Generating image data from Radio Sources and pre-processing images.
            - With help of <mark>Deep Learning</mark> identifying Type-1 Galaxies in those Images.
            - Trained different DL models and compared their performance for finest results.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University Of Mumbai
        caption: 2016 - 2018
        sub_title: MSc Computer Science
        quote: >
          Major in Computer Science Specialization in Machine Intelligence.
        description: | # this will include new lines to allow paragraphs
          University Department of Computer Science, is the oldest department started with a Master's level programme in Computer Science. 

      - layout: left
        title: University Of Mumbai
        caption: 2010 - 2015
        sub_title: BSc Physics
        quote: >
          The University of Mumbai is one of the oldest and premier Universities of India.
        description: | # this will include new lines to allow paragraphs  
          I studied in Bhavan's College which is one of the oldest and top most college in Mumbai.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Machine Learning some of my other interests and hobbies are:
      - Cycling
      - Gaming
      - Playing Cricket
      - Stargazing
      - Photography

      Look at this cool image.\
      ![Beach](images/beach.jpg "Beach")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
