# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: PATIL AKSHAY VILAS VAISHALI
title: Senior Data Scientist
email: akshaypatil15@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: akshaypatil15
github_username:  akshaypatil15
stackoverflow_username: "6459275"
instagram_username: chief_akshay
# twitter_username: akshaypatil15
# facebook_username: appy15
# pinterest_username: akshaypatil15
# youtube_username: "64113981"

# Additional icon links
additional_links:
- title: wordpress
  icon: fab fa-wordpress
  url: https://chiefakshaypatil.wordpress.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Akshay and I'm a senior data scientist with 3 years of industrial experience in building solutions for Computer Vision as well as Natural Language problems. Proven success in creating and deploying machine learning solutions.

  I am most skilled in: <mark>Python</mark> and <mark>Capturing Nature through lens</mark>

content:
  - title: Project # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Course Project
        # link: 
        # link_text: Project Website
        # additional_links:
        #  - title:  akshaypatil15/getTextFromPDF
        #    icon: fab fa-github
        #    url: https://github.com/Akshaypatil15/getTextFromPDF.git
          # - title:  Github page for project (eg. akshaypatil15/getTextFromPDF)
          #   icon: fab fa-github
          #   url: Link to project (eg. https://github.com/Akshaypatil15/getTextFromPDF.git)
        quote: >
          NEURAL NETWORK FOR CLASSIFICATION OF STARS AND GALAXIES.
        description: | # this will include new lines to allow paragraphs
          Developed a star-galaxy classification framework that uses a neural network model directly on the images from the <mark>Sloan Digital Sky Survey(SDSS)</mark>. Trained model using Convolution <mark>Neural Network</mark> with the help of <mark>TensorFlow</mark> library.

      - layout: left
        title: Pdf to Text
        link: https://github.com/Akshaypatil15/getTextFromPDF
        link_text: getTextFromPDF
        # additional_links:
        #  - title:  modern-resume-theme
        #    icon: fab fa-github
        #    url: boringcompany.com
          # - title:  Github page for project (eg. akshaypatil15/getTextFromPDF)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is one of the beginner project created by me.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way to learn <mark>GCP</mark> and it has since grown into a fully end-to-end python project. I have learned many skills after this and been I'm very proud of having this in my profile.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Quantech Data Science, Navi Mumbai
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Data Scientist
        caption: December 2019 - Present
        quote: >
          Designing solution architectures for data science/machine learning products.
        description: | # this will include new lines to allow paragraphs
            In the world of technology, automation is one of growing field. And for automation we basically use Machine Learning as well as Data Science techniques. Me and my team responsible to make machine learning model experiments and automated different procedures. We also handling development and maintenance of trained model's <mark>docker</mark> containers on cloud platforms. 
            
      - layout: left
        title: Cere Labs Pvt. Ltd., Mumbai
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: October 2018 - November 2019
        quote: >
          Artificial Intelligence research and deveploment.
        description: | # this will include new lines to allow paragraphs
            Collection and organization of large and complex datasets, conduct related pre-processing and cleaning methods. Analysis of gathered data to identify different patterns and insights from data. Develop algorithms using Deep Learning as well as Machine Learning to train models and get required information from data. Make these models servable using <mark>tensorflow serving</mark> so they can be easily used by the production team.
            
      - layout: left
        title: Cere Labs Pvt. Ltd., Mumbai
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Project Fellow
        caption: September 2018 - September 2018
        quote: >
          Contribute to aspects of research strategy within the department.
        description: | # this will include new lines to allow paragraphs
            Identifying methods for <mark>Text Detection</mark> as well as <mark>Recognition</mark> in Printed Documents. Maintaining digital record of the results in presentable format.
            
      - layout: left
        title: Cere Labs Pvt. Ltd., Mumbai
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Internship
        caption: Feburary 2018 - May 2018
        quote: >
          Galaxy Detection Using Artificial Intelligence.
        description: | # this will include new lines to allow paragraphs
            Generating image data from Radio Sources and preprocessing images. With help of <mark>Deep Learning</mark> identifying Type-1 Galaxies in those Images. Trained different DL models and compared their performance for finest results.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University Of Mumbai
        caption: 2016 - 2018
        sub_title: MSc Computer Science
        quote: >
          Major in Computer Science Specialization in Machine Intelligence.
        description: | # this will include new lines to allow paragraphs
          University Department of Computer Science, is the oldest department started with a Master’s level programme in Computer Science. 
          
      - layout: left
        title: University Of Mumbai
        caption: 2010 - 2015
        sub_title: BSc Physics
        quote: >
          The University of Mumbai is one of the oldest and premier Universities of India.
        description: | # this will include new lines to allow paragraphs  
          I studied in Bhavan's College which is one of the oldest and top most college in Mumbai.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Machine Leanring some of my other interests and hobbies are:
      - Cycling
      - Gaming
      - Playing Cricket
      - Photography

      Look at this cool image  
      ![Beach](images/beach.jpg "Beach")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
